FROM php:7.4-fpm

COPY ./conf.d/ /etc/php/conf.d/
RUN chmod 644 /etc/php/conf.d/php.ini

COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer

RUN apt-get update && \
    apt-get -y install unzip libpq-dev

RUN docker-php-ext-install pdo_mysql pdo_pgsql mysqli

WORKDIR /var/www/