FROM php:7.4-fpm

COPY ./conf.d/php.ini /etc/php/conf.d/php.ini
RUN chmod 644 /etc/php/conf.d/php.ini

COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer

RUN apt-get update && \
    apt-get -y install git libicu-dev libonig-dev libzip-dev unzip locales

WORKDIR /var/www/